### ISSUE TITLE
Make Grid cells clickable and on click, copy the Colour HEX code to clipboard 

### ISSUE THREAD

**Issue by SscSPs** [SscSPs/color#12]
The current grid doesn't have a way for letting user know the colour code thats shown in the grid.
It'll be useful if we show the hexcode when the mouse hovers over the cell.
And on clicking the cell, we can copy the colour hexcode to user's clipboard.

**Comment by lemmoor** [comment]
Hi, can i work on this?

**Comment by SscSPs** [comment]
Sure, feel free to work on anything
