### ISSUE TITLE
Add Live Demo link to the README.md

### ISSUE THREAD

**Issue by SscSPs** [SscSPs/color#30]
the app is live using the github pages, here's the link to it: 
https:/sscsps.github.io/color
Need to add this link to the readme so anyone can come and try it out

**Comment by shivam1317** [comment]
Can i work on this?

**Comment by SscSPs** [comment]
hey @shivam1317, this was worked on by @initmd already, you can def try working on any other issue present without asking and can directly submit the PR,

**Comment by SscSPs** [comment]
Thanks for helping out :)
