### ISSUE TITLE
Add a notification/toast/tooltip message to let user know when user clicks to let them know its copied

### ISSUE THREAD

**Issue by SscSPs** [SscSPs/color#33]
Currently, clicking on a cell in grid copies it to clipboard, but user doesn't get to know about it.
we need to add a way to let user know that it's copied.
there are a few options for showing that info to user:
1. show a notification on top right of the page to user
2. show a toast like message in the bottom centre of the page
3. show a pup down tooltip like thing showing that its copied!
4. replace the text shown in the cell from HEX code to text "Copied!" for 2 seconds or something

Suggestions are welcome!

**Comment by goldenPheonix02** [comment]
we can add a toast notification to show its copied which will stay on bottom of the screen for 2/3 seconds, can work on this.

**Comment by SscSPs** [comment]
sounds good, just a suggestion, add this as a component in its own file and use that,

**Comment by M-Rahul1** [comment]
> we can add a toast notification to show its copied which will stay on bottom of the screen for 2/3 seconds, can work on this.

I thought of the same. If you need help i can do it.

**Comment by piyshkmr** [comment]
i already did that please check pull request

**Comment by SscSPs** [comment]
Thanks guys, merged #45
