### ISSUE TITLE
App's meta description is still the one created from create-react-app, need to update it

### ISSUE THREAD

**Issue by SscSPs** [SscSPs/color#49]
The current description of the app is the one created by create-react-app 
"Web site created using create-react-app"

We should update it to show what this app really is, suggestions?

**Comment by jsvigneshkanna** [comment]
Please assign me this issue, will update to app working

**Comment by SscSPs** [comment]
Awesome, Go ahead and raise a PR

**Comment by SscSPs** [comment]
before you do raise a PR tho, can you share what description are you thinking of adding?

**Comment by jsvigneshkanna** [comment]
@SscSPs  what about `An online color picker tool`

**Comment by SscSPs** [comment]
it creates color palette, monochromatic palette, may be something along those lines

**Comment by jsvigneshkanna** [comment]
@SscSPs , what about
`Create a color palette online with Color Picker. Great for digital artists, designers, and web developers.`

or 
`Generate or browse beautiful color palette, monochromatic palette combinations for your designs.`

**Comment by SscSPs** [comment]
"Come and Find beautiful color combinations for your designs!"

how about that?

**Comment by jsvigneshkanna** [comment]
Works well, will update the same in code

**Comment by SscSPs** [comment]
because we should be adding more palettes in future, so setting it in descriptions feels a bit restrictive I guess

**Comment by jsvigneshkanna** [comment]
@SscSPs  PR: #50

**Comment by SscSPs** [comment]
merged #50 
closing this
