### ISSUE TITLE
Readme link live project

### ISSUE THREAD

**Issue by BrunoLagoa** [SscSPs/color#51]
It would be nice to open a new browser tab when clicking on live project, so the user wouldn't leave your project on github. If that makes sense to you, you can assign me that adjustment. Thanks.

**Comment by SscSPs** [comment]
Thanks! Sounds good, I'll assign it to you 🤗

**Comment by BrunoLagoa** [comment]
Hi, I'm going to need to close this issue, unfortunately github is not able to do that.

We tried with:
_config.yml
     kramdown

####<a href="https://sscsps.github.io/color" target="_blank">🎨 Click here for the live demo!</a>

#### [🎨 Click here for the live demo!](https://sscsps.github.io/color){:target="_blank" rel="noopener"}

all github, disabled. =(

**Comment by SscSPs** [comment]
Damn, that's a bummer 😕
Thanks for your efforts though 🤗😀
Welcome to work on any other part of the project ☺️
