### ISSUE TITLE
Make choose any color(text) a little better

### ISSUE THREAD

**Issue by Aakash441** [SscSPs/color#53]
Add a little css and add a fade effect.

**Comment by SscSPs** [comment]
Hey, thanks for the opening the issue, 
Can you elaborate on the change you want to make?

**Comment by Aakash441** [comment]
When the user will open the page, choose any color text which is above the color palette will be visible with a fade effect. I have tried it on my branch, it looks good.

**Comment by SscSPs** [comment]
Okay cool, sound awesome!
Can you raise a PR and also add the screenshot if possible 🤗

**Comment by Aakash441** [comment]
Ok I will, but since it's a visual effect it won't be visible in a screenshot. Should I email you the video?

**Comment by SscSPs** [comment]
Oh, in that case, i think unlisted YouTube upload should be good, so others can see as well :)

**Comment by CheoR** [comment]
@Aakash441 You can also do  a screen capture with Loom and upload a .gif video.

**Comment by Aakash441** [comment]
I uploaded the youtube video link in my PR.

**Comment by SscSPs** [comment]
Cool

**Comment by SscSPs** [comment]
PR merged #55
