### ISSUE TITLE
add margin to the heading. 

### ISSUE THREAD

**Issue by kusum-chowdhury** [SscSPs/color#54]
it sticks to the top of the page. it should be a little lower.

**Comment by Drex72** [comment]
Hey, can i work on this?

**Comment by SscSPs** [comment]
Sounds logical, @kusum-chowdhury do you want to work on it or should @Drex72 work on it? 

@Drex72 since @kusum-chowdhury created this issue, probably they want to work on it, so let them reply!

**Comment by kusum-chowdhury** [comment]
yeah i want to work on it.

**Comment by SscSPs** [comment]
Awesome! I'll assign it to you :)
