### ISSUE TITLE
Website not responsive on mobile devices.

### ISSUE THREAD

**Issue by shamimsikder** [SscSPs/color#70]
<h4>When viewing the website on mobile devices, the footer overlaps with other content on the page, making it difficult to interact with the website.</h4>

![sscsps github io_color_(iPhone SE)](https://user-images.githubusercontent.com/35293225/227479398-89ab7adf-4a44-442a-9081-160cf04d0065.png)

**Comment by SscSPs** [comment]
Hi, Thanks for reporting this, 
If you would like to fix this, you are welcome to, please raise a CR.
